repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-yaml
        exclude: "(conda/meta.yaml|.clang\\-format)$"
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: (tests.data)
      - id: double-quote-string-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: (tests.data|docs.make.bat)
      - id: trailing-whitespace
        exclude: (tests.data)
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.17.0"
    hooks:
    - id: pyupgrade
      args: [--py312-plus]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: tests
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        files: \.py(?:i)?
  - repo: https://github.com/myint/docformatter
    rev: "v1.7.5"
    hooks:
    - id: docformatter
      exclude: (tests.data)
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: "v0.6.13"
    hooks:
    - id: cmake-lint
    - id: cmake-format
      additional_dependencies: [pyyaml]
      types: [file]
      files: CMakeLists.txt
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
    - id: codespell
      exclude: "(.*plantuml|tests.data)"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        exclude: "(.*json)"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        exclude: "docs|typings"
        additional_dependencies:
          # Type stubs
          - types-setuptools
          # Typed libraries
          - dask
